version: '3.4'

services:
  moviecatalog.api:
    image: ${DOCKER_REGISTRY-}moviecatalogapi
    build:
      context: .
      dockerfile: MovieCatalog.API/Dockerfile
      args: 
       GIT_COMMIT: unspecified
       BUILD_TIME: unspecified
    container_name: moviecatalog_api
    ports:
        - "8000:80"
    env_file:
        - MovieCatalog.API/.env
    depends_on:
        - db
    healthcheck:
      test: curl --fail http://localhost:80/health || echo 1
      interval: 1s
      timeout: 3s
      retries: 60
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: moviecatalog_api_db
    volumes:
        - "my_db:/var/opt/mssql" 
    env_file:
        - MovieCatalog.API/.db.env
volumes:
  my_db: